custom.clearSchedule()
custom.setBeginTime(0, 0, 20)
custom.setRYGLightTime(1, 0, 0)
custom.sendMessageToMCU()
custom.setBeginTime(0, 0, 40)
custom.setRYGLightTime(0, 1, 0)
custom.sendMessageToMCU()
custom.setBeginTime(0, 1, 0)
custom.setRYGLightTime(0, 0, 1)
custom.sendMessageToMCU()
custom.updateModuleTime(0, 0, 0)
basic.forever(function () {
    serial.writeLine("" + custom.getNowTime(MyEnumTime.Hour) + custom.getNowTime(MyEnumTime.Minute) + custom.getNowTime(MyEnumTime.Second))
})
